cc_library(
    name = "gen",
    srcs = ["gen.cc"],
    hdrs = ["gen.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//ichneutae/bazel:label",
        "//ichneutae/bazel:workspace",
        "//ichneutae/generate:cc_build",
        "//ichneutae/generate:cc_guards",
        "//ichneutae/generate:cc_header",
        "//ichneutae/generate:cc_namespace",
        "//ichneutae/generate:cc_source",
        "//ichneutae/generate:cc_tests",
        "//ichneutae/os:files",
        "//ichneutae/os:path",
    ],
)
